### ISSUE TITLE
How to run test.py

### ISSUE THREAD

**Issue by ahsan856jalal** [ImagingLab/Colorizing-with-GANs#22]
when I run this command
python test.py --checkpoints-path ./checkpoints --test-input ./checkpoints/test --test-output ./checkpoints/output

I get this error

  File "/home/ahsanjalal/Colorizing-with-GANs/src/models.py", line 324, in __init__
    super(int, self).__init__(sess, options)
TypeError: super(type, obj): obj must be an instance or subtype of type

Even if I change the checkpoint to checkpoints/places365 , still same problem 
![test](https://user-images.githubusercontent.com/11498382/64780289-6c862300-d579-11e9-9046-5a7ccc379bce.png)

**Comment by bhargavipatel** [comment]
The class is not declared as "new-style" class.You can either do that, or add multiple inheritance. This issue is only with python version 2.
Simple solution, switch to python3.

**Comment by ZHANGMEIRONG** [comment]
when I run this command
zhangmeirong@amax:~/color3/Colorizing-with-GANs$ CUDA_VISIBLE_DEVICES=0 python3 test.py --checkpoints-path ./checkpoints --test-input ./checkpoints/test --test-output ./checkpoints/output

I get this error

Traceback (most recent call last):
  File "test.py", line 5, in <module>
    main(options)
  File "/data0/zhangmeirong/color3/Colorizing-with-GANs/src/main.py", line 26, in main
    model = Cifar10Model(sess, options)
  File "/data0/zhangmeirong/color3/Colorizing-with-GANs/src/models.py", line 287, in __init__
    super(Cifar10Model, self).__init__(sess, options)
  File "/data0/zhangmeirong/color3/Colorizing-with-GANs/src/models.py", line 25, in __init__
    self.dataset_train = self.create_dataset(True)
  File "/data0/zhangmeirong/color3/Colorizing-with-GANs/src/models.py", line 321, in create_dataset
    augment=self.options.augment)
  File "/data0/zhangmeirong/color3/Colorizing-with-GANs/src/dataset.py", line 90, in __init__
    super(Cifar10Dataset, self).__init__(CIFAR10_DATASET, path, training, augment)
  File "/data0/zhangmeirong/color3/Colorizing-with-GANs/src/dataset.py", line 19, in __init__
    self.data = []
 AttributeError: can't set attribute


 I don't known how to solve this problem?
