### ISSUE TITLE
Attribute error, please help

### ISSUE THREAD

**Issue by MrLassagna** [ImagingLab/Colorizing-with-GANs#23]
python test.py --checkpoints-path checkpoints/cifar10 --test-input checkpoints/test --test-output checkpoints/output
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    from src import ModelOptions, main
  File "C:\Projects\Image-Colorizing-with-GAN\src\__init__.py", line 2, in <module>
    from .models import *
  File "C:\Projects\Image-Colorizing-with-GAN\src\models.py", line 9, in <module>
    from .networks import Generator, Discriminator
  File "C:\Projects\Image-Colorizing-with-GAN\src\networks.py", line 3, in <module>
    from .ops import conv2d, conv2d_transpose, pixelwise_accuracy
  File "C:\Projects\Image-Colorizing-with-GAN\src\ops.py", line 6, in <module>
    tf.nn.softmax_cross_entropy_with_logits_v2
AttributeError: module 'tensorflow_core._api.v2.nn' has no attribute 'softmax_cross_entropy_with_logits_v2'

**Comment by Angelina7329** [comment]
Maybe tf version cause this error

**Comment by Angelina7329** [comment]
Maybe tf version cause this error
